# Generated by Django 4.1.7 on 2024-07-30 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_alter_article_slug_alter_article_title_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Clap",
        ),
    ]
