# Generated by Django 4.1.7 on 2024-08-19 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0003_delete_clap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleview",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_views",
                to=settings.AUTH_USER_MODEL,
                verbose_name="viewed by",
            ),
        ),
    ]
