#!/bin/bash

#Exit immediately if a command exits with a non-zero status.
set -o errexit
#The return value of a pipeline is the status of the last command to exit with a non-zero status, or zero if no command exited with a non-zero status
set -o pipefail
#Treat unset variables and parameters as an error when performing parameter expansion.
set -o nounset

python manage.py migrate --no-input
python manage.py collectstatic --no-input
exec python manage.py runserver 0.0.0.0:8000

