upstream api {
  server api:8000;
}

server {

  client_max_body_size 20M;

  listen 80;

  location /api/v1/ {

    proxy_pass http://api;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_redirect off;

  }

  #configuration pour les métriques de Nginx
  location /nginx_status {
    stub_status on;
    access_log off;
    allow 127.0.0.1;
    allow 172.16.0.0/12; # Replace with your local network
    deny all;
  }

  location /hidden {
    proxy_pass http://api;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_redirect off;
  }

  location /redoc {

    proxy_pass http://api;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_redirect off;

  }

  location /staticfiles/ {
    autoindex on;
    alias /app/staticfiles/;
  }

  location /mediafiles/ {
    alias /app/mediafiles/;
  }

}