#!/bin/bash

#Exit immediately if a command exits with a non-zero status.
set -o errexit
#The return value of a pipeline is the status of the last command to exit with a non-zero status, or zero if no command exited with a non-zero status
set -o pipefail
#Treat unset variables and parameters as an error when performing parameter expansion.
set -o nounset

python /app/manage.py collectstatic --noinput
python /app/manage.py migrate

exec /usr/local/bin/gunicorn apipro.wsgi --bind 0.0.0.0:1998 --chdir=/app